application:
  max-allowed-books: 15
server:
  port: 8081
spring:
  datasource:
    username: wch
    password: password
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  hibernate:
    ddl-auto: update
    show-sql: true
    format_sql: true
    use_sql_comments: true