application:
  max-allowed-books: 15
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksDatabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hbm2ddl: update
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
