application:
  max-allowed-books: 15
server:
  port: 8081
#spring:
#  datasource:
#    username: wch
#    password: password
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#  hibernate:
#    hbm2ddl.auto: update
#    ddl-auto: update
#    show-sql: true
#    format_sql: true
#    use_sql_comments: true
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    #database: h2 #same as database-platform, it doesn't effect schema-{platform}.sql and data-{platform}.sql names
    #database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test #ALWAYS, EMBEDDED or NEVER will be calculated from h2
    username: wch
    password: password
    driverClassName: org.h2.Driver
    #initialization-mode: always # deprecated, moved to under sql.init, DON'T USE
    #platform: h2 #deprecated, moved to under sql.init, , DON'T USE
  sql:
    init:
      #continue-on-error: true
      mode: ALWAYS
      platform: h2 #it effect schema-{platform}.sql and data-{platform}.sql names
  h2:
    console:
      enabled: true
#      path: /h2

logging:
  level:
    root: INFO
    #org.hibernate.SQL: TRACE
    #spring.sql: TRACE
    #javax.sql: TRACE
    #    org.h2.jdbc: TRACE
    org.springframework.jdbc: TRACE
debug: false


#-secutity================================================================
#spring:
#  application:
#    name: security-security
#  datasource:
#    url: jdbc:h2:mem:security-security
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855